// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ReportAppDbContext))]
    [Migration("20210506141226_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entity.ExportHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExportDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("ExportHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExportDateTime = new DateTime(2021, 5, 5, 16, 12, 25, 755, DateTimeKind.Local).AddTicks(8295),
                            Name = "Test1",
                            PlaceId = 1,
                            User = "User1"
                        },
                        new
                        {
                            Id = 2,
                            ExportDateTime = new DateTime(2021, 5, 4, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5861),
                            Name = "Test2",
                            PlaceId = 2,
                            User = "User1"
                        },
                        new
                        {
                            Id = 3,
                            ExportDateTime = new DateTime(2021, 5, 3, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5903),
                            Name = "Test3",
                            PlaceId = 3,
                            User = "User1"
                        },
                        new
                        {
                            Id = 4,
                            ExportDateTime = new DateTime(2021, 5, 2, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5910),
                            Name = "Test4",
                            PlaceId = 4,
                            User = "User1"
                        },
                        new
                        {
                            Id = 5,
                            ExportDateTime = new DateTime(2021, 5, 1, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5914),
                            Name = "Test5",
                            PlaceId = 4,
                            User = "User2"
                        },
                        new
                        {
                            Id = 6,
                            ExportDateTime = new DateTime(2021, 5, 1, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5918),
                            Name = "Test6",
                            PlaceId = 5,
                            User = "User2"
                        },
                        new
                        {
                            Id = 7,
                            ExportDateTime = new DateTime(2021, 5, 11, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5922),
                            Name = "Test7",
                            PlaceId = 1,
                            User = "User2"
                        },
                        new
                        {
                            Id = 8,
                            ExportDateTime = new DateTime(2021, 5, 7, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5936),
                            Name = "Test8",
                            PlaceId = 1,
                            User = "User2"
                        },
                        new
                        {
                            Id = 9,
                            ExportDateTime = new DateTime(2021, 5, 8, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5943),
                            Name = "Test9",
                            PlaceId = 1,
                            User = "User2"
                        },
                        new
                        {
                            Id = 10,
                            ExportDateTime = new DateTime(2021, 5, 9, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5947),
                            Name = "Test10",
                            PlaceId = 2,
                            User = "User3"
                        },
                        new
                        {
                            Id = 11,
                            ExportDateTime = new DateTime(2021, 5, 10, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5950),
                            Name = "Test11",
                            PlaceId = 2,
                            User = "User3"
                        },
                        new
                        {
                            Id = 12,
                            ExportDateTime = new DateTime(2021, 5, 11, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5954),
                            Name = "Test12",
                            PlaceId = 2,
                            User = "User3"
                        },
                        new
                        {
                            Id = 13,
                            ExportDateTime = new DateTime(2021, 5, 11, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5959),
                            Name = "Test13",
                            PlaceId = 2,
                            User = "User3"
                        },
                        new
                        {
                            Id = 14,
                            ExportDateTime = new DateTime(2021, 5, 11, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5962),
                            Name = "Test14",
                            PlaceId = 3,
                            User = "User4"
                        },
                        new
                        {
                            Id = 15,
                            ExportDateTime = new DateTime(2021, 5, 11, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5969),
                            Name = "Test15",
                            PlaceId = 3,
                            User = "User4"
                        },
                        new
                        {
                            Id = 16,
                            ExportDateTime = new DateTime(2021, 5, 1, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5973),
                            Name = "Test16",
                            PlaceId = 3,
                            User = "User4"
                        },
                        new
                        {
                            Id = 17,
                            ExportDateTime = new DateTime(2021, 5, 1, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5978),
                            Name = "Test17",
                            PlaceId = 3,
                            User = "User5"
                        },
                        new
                        {
                            Id = 18,
                            ExportDateTime = new DateTime(2021, 5, 1, 16, 12, 25, 759, DateTimeKind.Local).AddTicks(5982),
                            Name = "Test17",
                            PlaceId = 3,
                            User = "User6"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Place1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Place2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Place3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Place4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Place5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Place6"
                        });
                });

            modelBuilder.Entity("Domain.Entity.ExportHistoryEntry", b =>
                {
                    b.HasOne("Domain.Entity.Place", "Place")
                        .WithMany("ExportHistoryEntry")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Domain.Entity.Place", b =>
                {
                    b.Navigation("ExportHistoryEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
